### ISSUE TITLE
Sorting doesn't work for custom fields

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream-Custom-Fields#70]
The up and down arrows aren't working for Custom Fields. You can see the 3 columns on the right:

<img width="1072" alt="Screen Shot 2019-06-06 at 9 24 00 AM" src="https://user-images.githubusercontent.com/3868028/59036266-e9985280-883c-11e9-9aa7-336aaf09c593.png">

**Comment by stevejburge** [comment]
One more report for this today

**Comment by sergeidevstar001** [comment]
Fixed

**Comment by oraclerob** [comment]
@stevejburge there is a pull request #775 for this. Not sure why this didn't make the release? Be good if it is actually solved I can then merge it for our customer.

**Comment by stevejburge** [comment]
Sorry, we had a big backlog for the last release. We'll make sure this makes the next one
