### ISSUE TITLE
Checkbox results don't show on the page

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream-Custom-Fields#71]
- Create a "Checkbox" custom fields. 
- Set "Display as column" to Yes
- Enter data
- The data doesn't show on the frontend. 2 of these 3 columns are checkboxes:

<img width="955" alt="Screen Shot 2019-06-06 at 9 26 59 AM" src="https://user-images.githubusercontent.com/3868028/59036429-472c9f00-883d-11e9-993a-223d6ca8bbe5.png">

**Comment by sergeidevstar001** [comment]
Problem : $field->options[$selected] is not set value on
   UpStream-Custom-Fields / CustomFields / Pages / Project.php
   $field->options : options list
Solution : it need to change $field->options[$selected] to $field->options[$label]
