### ISSUE TITLE
Add Custom Fields to Clients

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream-Custom-Fields#77]
Good idea from a customer

> It would be nice if Custom Fields was available not only for milestone, task, calendar, etc... but also for Clients.

**Comment by stevejburge** [comment]
This is where fields could be added <img width="1233" alt="clients" src="https://user-images.githubusercontent.com/3868028/60590999-6864aa80-9d6b-11e9-8395-2ac4ed63b835.png">

**Comment by andergmartins** [comment]
@sergeidevstar001 Please, I have found one issue. In the custom fields list it is not displaying "Clients":

<img width="1277" alt="Screen Shot 2019-07-10 at 15 34 55" src="https://user-images.githubusercontent.com/407131/60995270-937d6a00-a328-11e9-832e-369f3f988172.png">

**Comment by andergmartins** [comment]
Another issue, the option Display as Column is not working. 

<img width="1292" alt="Screen Shot 2019-07-10 at 15 39 21" src="https://user-images.githubusercontent.com/407131/60995554-16062980-a329-11e9-829c-63fc37e83a4e.png">

If enabled, it should display a column here for the custom field and the data:

<img width="1282" alt="Screen Shot 2019-07-10 at 15 39 41" src="https://user-images.githubusercontent.com/407131/60995565-1d2d3780-a329-11e9-875e-ed3932ac0207.png">

**Comment by andergmartins** [comment]
"Used on" is fixed, but the "Display as column" not yet.

https://github.com/upstreamplugin/UpStream-Custom-Fields/issues/77#issuecomment-510180685

**Comment by andergmartins** [comment]
@sergeidevstar001 it is almost there. The column is displayed now, but it doesn't recognise the option to not show the column. It always display the column. It should check the field's setting.

<img width="1118" alt="Screen Shot 2019-07-17 at 10 09 25" src="https://user-images.githubusercontent.com/407131/61378186-354a0d00-a87b-11e9-9e88-912665941fb6.png">

**Comment by sergeidevstar001** [comment]
Sorry, I forgot it, will fix it.
