### ISSUE TITLE
Single checkboxes don't save data

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream-Custom-Fields#83]
Create a Custom field like this:

<img width="925" alt="Screen Shot 2019-07-16 at 5 09 08 PM" src="https://user-images.githubusercontent.com/3868028/61306322-a8587280-a7ec-11e9-94a7-8b7b49407e7e.png">

On the frontend, you can use the checkbox and record data.

However, open the checkbox a second time and the data is lost

**Comment by sergeidevstar001** [comment]
I found problem.
It related with 2 files.
UpStream-Custom-Fields / CustomFields / Pages / Project.php
UpStream-Frontend-Edit / assets / js / project.js
Will fix it soon.

**Comment by sergeidevstar001** [comment]
Fixed it.
Problem : 
  It's set wrong id on modal
Changed files:
 - UpStream-Custom-Fields / CustomFields / Pages / Project.php
 - UpStream-Frontend-Edit / assets / js / project.js

**Comment by andergmartins** [comment]
@sergeidevstar001 I can confirm that the original issue is fixed. The checkbox values are now saved and correct displayed. But there is a new PHP Notice:

<img width="646" alt="Screen Shot 2019-07-17 at 10 17 59" src="https://user-images.githubusercontent.com/407131/61378677-4fd0b600-a87c-11e9-8a1b-de2205c736b5.png">

**Comment by andergmartins** [comment]
Looks good here. Thanks.
